# Generated by Django 4.2.6 on 2023-10-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pais_options_alter_tipoatuacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pais')),
            ],
        ),
    ]
