# Generated by Django 4.2.6 on 2023-10-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_atuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuacao',
            name='personagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
